apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simple-website.fullname" . }}-metrics-reader
  labels:
    {{- include "simple-website.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "simple-website.fullname" . }}-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "simple-website.fullname" . }}
    namespace: {{ .Release.Namespace }}
